### ISSUE TITLE
Thread 'main' panic when running example

### ISSUE THREAD

**Issue by kflak** [Entscheider/freenect-rs#1] opened 2020-05-09 11:14 UTC
Hi, and thanks for porting libfreenect! Been itching to learn Rust for a while, and porting some openframeworks/kinect stuff seems like a good way to do so :-) 

I am trying to build the example project by running 

```
cargo run --release --example kinect_live
```
and it compiles fine (minus a couple of nags about deprecated item 'try'), but then I get this:
```
     Running `target/release/examples/kinect_live`
Found 1 devices, use first
thread 'main' panicked at 'Tried to get contents of a not-ready EnvHandler.', /home/kf/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.7.8/src/env.rs:100:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: winit::api::wayland::context::WaylandContext::create_window
  10: winit::api::wayland::window::Window::new
  11: winit::window::<impl winit::WindowBuilder>::build
  12: glutin::platform::platform::wayland::Window::new
  13: glutin::window::<impl glutin::WindowBuilder>::build
  14: glium::backend::glutin_backend::<impl glium::DisplayBuild for glutin::WindowBuilder>::build_glium_debug
  15: kinect_live::glwinhelp::imgwin::ImgWindow::new
  16: kinect_live::main
  17: std::rt::lang_start::{{closure}}
  18: std::panicking::try::do_call
  19: __rust_maybe_catch_panic
  20: std::rt::lang_start_internal
  21: main
  22: __libc_start_main
  23: _start
```
System: arch linux 5.6.10-rt5-1-rt, swaywm 1.4.

No idea where to start looking for a fix on this, unfortunately...

**Comment by kflak** [comment] 2020-06-16 12:22
Seems the problem is wayland-related: the example runs fine on i3, but not on sway...

**Comment by Entscheider** [comment] 2020-06-18 11:04
Hi. Sorry for this late reply and thank you for using my stuff and reporting issues for it. I'm happy that this code is still in use.

I wrote this project a few years ago, at a time when there was no question mark operator, so using `try!` was the preferred approach back then. 

Your description and analysis seems real helpful. Looking at your backtrace I also suspect that this is a wayland specific problem. I'm going to test it the next days. As far as I can see, this only affects an example, but the library itself is still functional.

Maybe updating the glium dependecy is enough for fixing or I have to write a new example, we'll see.

Nevertheless it's nice to read about your porting project. Choosing Rust is a bit challenging at first but really worth it in my opinion. Together with archlinux and wayland you should have a solid development experience ;)

**Comment by kflak** [comment] 2020-06-18 15:42
Cool!

I’m also wondering if this issue is somehow related: https://github.com/nannou-org/nannou/issues/618
Been having wayland-related troubles getting some of the nannou examples running as well...

**Comment by Entscheider** [comment] 2020-06-24 20:13
Unfortunately I was not able to reproduce your bug under Arch-Linux and Sway.
Based on your error message, I would wildly guess that some environment variables could be wrong. 

However, I updated my dependencies to the latest versions and you should at least see a different error message now. At best, it should work. You can try it by checking out the branch [bugfix/1-example-panic-on-wayland](https://github.com/Entscheider/freenect-rs/tree/bugfix/1-example-panic-on-wayland).

**Comment by kflak** [comment] 2020-06-26 11:17
The fix seems to work! Thanks a lot! I am now able to run the example on sway with no issue. The only quibble seems to be that the tilt motor is getting stuck in the lowest position. I will try to investigate a bit more when I have some time, maybe it's just my kinect that is in a bad mood...

**Comment by Entscheider** [comment] 2020-06-26 21:35
Great. If you have further hints that the motor problem is caused by this project, please open a new issue.

I will close this issue. Good luck with your project.

**Closed as completed by Entscheider** 2020-06-26 21:35 UTC
Labels: bug
